import CryptoKit
import Foundation

/// The names of the files the vault holds. Centralized so "what is actually stored on this phone?"
/// is answerable by reading one declaration rather than grepping for string literals.
enum VaultFile {
    /// Normalized medications, therapy tasks and allergies — the bulk of the PHI.
    static let careRecord = "care-record"
    /// Reminders the user explicitly approved. These drive local notifications.
    static let approvedReminders = "approved-reminders"
    /// Proposal IDs the user skipped, so Remli does not re-propose them on every import.
    static let skippedProposals = "skipped-proposals"

    /// Every file the vault is allowed to contain. `wipeAll()` does not depend on this list — it
    /// clears the directory wholesale — but a "what's stored" screen can enumerate it.
    static let all: [String] = [careRecord, approvedReminders, skippedProposals]
}

/// AES-GCM file storage for everything Remli knows about a patient.
///
/// Three separate protections are stacked here, because each one covers a case the others do not:
///
/// 1. **AES-GCM with a Keychain-held key.** Protects against the ciphertext being read anywhere
///    other than this device — an extracted app container, a forensic image, a stray file copy.
///    GCM rather than CBC-with-a-bolted-on-MAC so tampering fails loudly instead of decoding into
///    plausible-looking nonsense; a silently altered dosage instruction is the worst outcome here.
/// 2. **`.completeFileProtection`.** The file is unreadable by anything, including this app, while
///    the phone is locked. This is what stops a background task from touching health data at 3am.
/// 3. **`isExcludedFromBackup`.** Ciphertext never enters an iCloud or Finder backup. Combined
///    with a `ThisDeviceOnly` key this is belt and braces, but it also keeps a user's iCloud
///    storage free of an opaque multi-megabyte blob they cannot explain.
///
/// Application Support rather than Documents: this is app-managed state, not user documents, and
/// it must not appear in the Files app.
final class EncryptedVault {
    /// Sealed boxes are stored combined (nonce ‖ ciphertext ‖ tag). A fresh random nonce is
    /// generated by CryptoKit for every seal, so rewriting the same snapshot never produces the
    /// same bytes — nonce reuse under a fixed key is the one way to actually break AES-GCM.
    private let keyStore: VaultKeyStore
    private let fileManager: FileManager
    private let directoryName: String
    private let lock = NSLock()
    private var cachedKey: SymmetricKey?

    init(
        keyStore: VaultKeyStore = VaultKeyStore(),
        directoryName: String = "Vault",
        fileManager: FileManager = .default
    ) {
        self.keyStore = keyStore
        self.directoryName = directoryName
        self.fileManager = fileManager
    }

    // MARK: - Location

    /// `…/Library/Application Support/Vault`. Resolved lazily so constructing a vault never
    /// touches the filesystem or the Keychain — that matters because `VaultStore` is built during
    /// SwiftUI scene setup, on the main thread.
    var directoryURL: URL {
        let base = (try? fileManager.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: false
        )) ?? URL(fileURLWithPath: NSTemporaryDirectory())
        return base.appendingPathComponent(directoryName, isDirectory: true)
    }

    func fileURL(for name: String) -> URL {
        directoryURL.appendingPathComponent(Self.sanitize(name)).appendingPathExtension("vault")
    }

    func exists(_ name: String) -> Bool {
        fileManager.fileExists(atPath: fileURL(for: name).path)
    }

    // MARK: - Reading and writing

    /// Encrypts and stores `value`. Overwrites atomically, so a crash mid-write leaves the previous
    /// ciphertext intact rather than a half-written file that would fail authentication.
    func write<T: Encodable>(_ value: T, to name: String) throws {
        let plaintext: Data
        do {
            plaintext = try Self.makeEncoder().encode(value)
        } catch {
            throw VaultError.encodeFailed(name: name, underlyingDescription: String(describing: error))
        }

        let key = try resolveKey()
        let sealed: Data
        do {
            sealed = try AES.GCM.seal(plaintext, using: key).combined ?? Data()
        } catch {
            throw VaultError.encodeFailed(name: name, underlyingDescription: String(describing: error))
        }
        guard !sealed.isEmpty else {
            throw VaultError.encodeFailed(name: name, underlyingDescription: "empty sealed box")
        }

        try ensureDirectory()
        let url = fileURL(for: name)
        do {
            try sealed.write(to: url, options: [.atomic, .completeFileProtection])
        } catch {
            throw VaultError.fileSystem(operation: "write \(name)", underlyingDescription: String(describing: error))
        }
        // An atomic write replaces the inode, so the exclusion flag has to be re-applied every
        // time rather than set once at creation.
        try excludeFromBackup(url)
    }

    /// Decrypts and decodes a stored value.
    ///
    /// Returns nil when the file simply is not there — a first launch, or a value the user has
    /// never created. Throws when the file exists but cannot be read, because silently returning
    /// nil there would look identical to "you have no medications", and quietly losing a
    /// medication list is not a failure mode this app is allowed to have.
    func read<T: Decodable>(_ type: T.Type, from name: String) throws -> T? {
        let url = fileURL(for: name)
        guard fileManager.fileExists(atPath: url.path) else { return nil }

        let sealedData: Data
        do {
            sealedData = try Data(contentsOf: url)
        } catch {
            throw VaultError.fileSystem(operation: "read \(name)", underlyingDescription: String(describing: error))
        }
        guard !sealedData.isEmpty else { return nil }

        let key = try resolveKey()
        let plaintext: Data
        do {
            let box = try AES.GCM.SealedBox(combined: sealedData)
            plaintext = try AES.GCM.open(box, using: key)
        } catch {
            // Wrong key, truncation, or tampering. Authenticated encryption deliberately does not
            // tell us which, so neither do we.
            throw VaultError.decryptionFailed(name: name)
        }

        do {
            return try Self.makeDecoder().decode(T.self, from: plaintext)
        } catch {
            throw VaultError.decodeFailed(name: name, underlyingDescription: String(describing: error))
        }
    }

    // MARK: - Deleting

    func delete(_ name: String) throws {
        let url = fileURL(for: name)
        guard fileManager.fileExists(atPath: url.path) else { return }
        do {
            try fileManager.removeItem(at: url)
        } catch {
            throw VaultError.fileSystem(operation: "delete \(name)", underlyingDescription: String(describing: error))
        }
    }

    /// Removes the whole vault directory.
    ///
    /// This reclaims the space. It is *not* the security-relevant half of "delete everything" —
    /// `VaultKeyStore.destroyKey()` is, because unlinking a file says nothing about the blocks that
    /// still hold it. Callers doing a full erase should do both, key last.
    func wipeAll() throws {
        let url = directoryURL
        guard fileManager.fileExists(atPath: url.path) else { return }
        do {
            try fileManager.removeItem(at: url)
        } catch {
            throw VaultError.fileSystem(operation: "wipe vault", underlyingDescription: String(describing: error))
        }
    }

    // MARK: - Coding

    /// ISO 8601 on both sides. Dates in this vault are clinical timestamps — an `authoredOn`, an
    /// `importedAt` — and they must survive a locale or OS change unambiguously. `.deferredToDate`
    /// would store a bare Double whose epoch is a Foundation implementation detail.
    static func makeEncoder() -> JSONEncoder {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.sortedKeys]
        return encoder
    }

    static func makeDecoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }

    // MARK: - Private

    /// The key is fetched once and held in memory for the process lifetime. Repeated Keychain
    /// round-trips on every write would be slower and no safer: while the app is running and the
    /// device is unlocked, the key is already in this process's address space.
    private func resolveKey() throws -> SymmetricKey {
        lock.lock()
        defer { lock.unlock() }
        if let cachedKey { return cachedKey }
        let key = try keyStore.loadOrCreateKey()
        cachedKey = key
        return key
    }

    /// Drops the in-memory key. Called after `destroyKey()` so a subsequent write generates a new
    /// key rather than re-encrypting under one the Keychain no longer has.
    func forgetCachedKey() {
        lock.lock()
        cachedKey = nil
        lock.unlock()
    }

    private func ensureDirectory() throws {
        let url = directoryURL
        guard !fileManager.fileExists(atPath: url.path) else { return }
        do {
            try fileManager.createDirectory(
                at: url,
                withIntermediateDirectories: true,
                attributes: [.protectionKey: FileProtectionType.complete]
            )
        } catch {
            throw VaultError.fileSystem(
                operation: "create vault directory",
                underlyingDescription: String(describing: error)
            )
        }
        try excludeFromBackup(url)
    }

    private func excludeFromBackup(_ url: URL) throws {
        var mutableURL = url
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        do {
            try mutableURL.setResourceValues(values)
        } catch {
            throw VaultError.fileSystem(
                operation: "exclude \(url.lastPathComponent) from backup",
                underlyingDescription: String(describing: error)
            )
        }
    }

    /// Filenames are app-chosen constants, never user or clinical text. This is a defensive
    /// backstop so a future caller cannot accidentally put a medication name — PHI — into a path
    /// that the OS, spotlight indexing, or a crash log might surface in the clear.
    private static func sanitize(_ name: String) -> String {
        let allowed = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_")
        let cleaned = String(name.unicodeScalars.map { allowed.contains($0) ? Character($0) : "-" })
        return cleaned.isEmpty ? "unnamed" : cleaned
    }
}
